-- Recipe definitions. All output decisions are made server-side from this file.
-- Fields:
--   id (unique), category, label, duration (ms per unit), ingredients { item = count },
--   output { item = count }, xp, minLevel, failChance (0-1), skillCheck (ox_lib args),
--   unlock = 'blueprint' (requires consumed blueprint metadata.recipe == id) | nil,
--   durabilityUse = { item = percent } (degradable tools consumed by wear, not removed)
ImperialCraftingRecipes = {
    -- ── tools ──
    {
        id = 'craft_lockpick',
        category = 'tools',
        label = 'Lockpick',
        duration = 6000,
        ingredients = { metalscrap = 2, plastic = 1 },
        output = { lockpick = 1 },
        xp = 4,
        minLevel = 0,
        failChance = 0.05,
        skillCheck = { 'easy', 'easy' },
    },
    {
        id = 'craft_toolkit',
        category = 'tools',
        label = 'Toolkit',
        duration = 9000,
        ingredients = { steel = 4, plastic = 2, component_mechanical = 1 },
        output = { toolkit = 1 },
        xp = 8,
        minLevel = 1,
    },
    {
        id = 'craft_radio',
        category = 'tools',
        label = 'Radio',
        duration = 8000,
        ingredients = { component_electronics = 2, plastic = 2, copper = 2 },
        output = { radio = 1 },
        xp = 8,
        minLevel = 1,
    },
    {
        id = 'craft_fishing_rod',
        category = 'camping',
        label = 'Fishing Rod',
        duration = 8000,
        ingredients = { plank = 2, plastic = 2, metalscrap = 1 },
        output = { fishing_rod = 1 },
        xp = 6,
    },

    -- ── repair ──
    {
        id = 'craft_repairkit',
        category = 'repair',
        label = 'Repair Kit',
        duration = 8000,
        ingredients = { steel = 3, rubber = 2, component_mechanical = 1 },
        output = { repairkit = 1 },
        xp = 6,
    },
    {
        id = 'craft_advrepairkit',
        category = 'mechanical',
        label = 'Advanced Repair Kit',
        duration = 14000,
        ingredients = { steel = 6, rubber = 3, component_mechanical = 3, component_electronics = 1 },
        output = { advancedrepairkit = 1 },
        xp = 14,
        minLevel = 2,
        durabilityUse = { toolkit = 5 },
    },
    {
        id = 'craft_cleaningkit',
        category = 'repair',
        label = 'Weapon Cleaning Kit',
        duration = 7000,
        ingredients = { plastic = 2, rubber = 1 },
        output = { cleaningkit = 1 },
        xp = 5,
    },

    -- ── medical (EMS bench) ──
    {
        id = 'craft_bandage',
        category = 'medical',
        label = 'Bandage',
        duration = 4000,
        ingredients = { cotton = 2 },
        output = { bandage = 1 },
        xp = 3,
    },
    {
        id = 'craft_ifaks',
        category = 'medical',
        label = 'IFAK',
        duration = 12000,
        ingredients = { bandage = 2, painkillers = 1, plastic = 1 },
        output = { ifaks = 1 },
        xp = 10,
        minLevel = 2,
    },

    -- ── farming processing (grain mill: 'processing') ──
    {
        id = 'mill_flour',
        category = 'processing',
        label = 'Mill Flour',
        duration = 6000,
        ingredients = { wheat = 4 },
        output = { flour = 1 },
        xp = 3,
    },
    {
        id = 'press_sugar',
        category = 'processing',
        label = 'Press Sugar',
        duration = 6000,
        ingredients = { sugarcane = 3 },
        output = { sugar = 1 },
        xp = 3,
    },
    {
        id = 'pack_produce_box',
        category = 'packing',
        label = 'Pack Produce Box',
        duration = 7000,
        -- 'anyProduce' pseudo-ingredient handled server-side: any 10 produce-type items
        anyProduce = 10,
        ingredients = {},
        output = { produce_box = 1 },
        xp = 4,
    },

    -- ── lumber (sawmill only) ──
    {
        id = 'saw_planks',
        category = 'lumber',
        label = 'Saw Planks',
        duration = 5000,
        ingredients = { log = 1 },
        output = { plank = 2 },
        xp = 3,
    },

    -- ── criminal tools (hidden benches; see docs/14) ──
    {
        id = 'craft_advlockpick',
        category = 'criminal_tools',
        label = 'Advanced Lockpick',
        duration = 12000,
        ingredients = { lockpick = 2, steel = 3, component_mechanical = 1 },
        output = { advancedlockpick = 1 },
        xp = 10,
        failChance = 0.1,
        skillCheck = { 'easy', 'medium' },
    },
    {
        id = 'craft_hacking_device',
        category = 'criminal_tools',
        label = 'Hacking Device',
        duration = 18000,
        ingredients = { component_electronics = 4, trojan_usb = 1, plastic = 2 },
        output = { hacking_device = 1 },
        xp = 16,
        minLevel = 2,
        unlock = 'blueprint',
        failChance = 0.15,
        skillCheck = { 'medium', 'medium' },
    },
    {
        id = 'craft_fake_plate',
        category = 'criminal_tools',
        label = 'Fake Plate',
        duration = 15000,
        ingredients = { aluminum = 4, plastic = 2 },
        output = { fake_plate = 1 },
        xp = 12,
        minLevel = 1,
    },
    {
        id = 'craft_signal_jammer',
        category = 'criminal_tools',
        label = 'Signal Jammer',
        duration = 20000,
        ingredients = { component_electronics = 5, copper = 4, plastic = 2 },
        output = { signal_jammer = 1 },
        xp = 18,
        minLevel = 3,
        unlock = 'blueprint',
        failChance = 0.2,
    },
    {
        id = 'craft_thermite',
        category = 'criminal_weapons',
        label = 'Thermite Charge',
        duration = 22000,
        ingredients = { aluminum = 6, chem_supplies = 2, component_electronics = 1 },
        output = { thermite = 1 },
        xp = 20,
        minLevel = 3,
        unlock = 'blueprint',
        failChance = 0.2,
        skillCheck = { 'medium', 'hard' },
    },
    {
        id = 'craft_armour_plate',
        category = 'criminal_weapons',
        label = 'Armour Plate',
        duration = 16000,
        ingredients = { steel = 8, cotton = 4 },
        output = { armour_plate = 1 },
        xp = 14,
        minLevel = 2,
    },
    {
        id = 'craft_ammo_components',
        category = 'criminal_weapons',
        label = 'Ammunition Components',
        duration = 10000,
        ingredients = { metalscrap = 4, chem_supplies = 1 },
        output = { ammo_components = 2 },
        xp = 8,
        minLevel = 1,
    },
}
